### PR TITLE
Change names of servlet based server spans

### LINKED ISSUE #391: Wrong span names for server HTTP spans
Can be considered as part of #233.

Several auto-instrumentations which create "server http" spans currently use simply "HTTP $method" as span name. This seem to violate the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md). E.g. `Servlet2Advice` and `Servlet3Advice`

### PR DESCRIPTION
**Pull request by iNikem**
Fixes #391 

Please start review with "instrumentation/servlet/README.md" file.

I have not changed Grizzly instrumentation, because their tests are not so easy changeable. I would like to address #423 next and extract common parts in Servlet instrumentations to a common decorator. This probably may lead to having a common decorator for the majority of http server spans. Then their names can be unified further.

### CODE REVIEW

File: instrumentation/servlet/src/main/java/io/opentelemetry/auto/instrumentation/servlet/http/HttpServletInstrumentation.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ public static SpanWithScope start(@Advice.Origin final Method method) {
       final Span span =
           TRACER
               .spanBuilder(DECORATE.spanNameForMethod(method))
-              .setSpanKind(Kind.SERVER)
+              .setSpanKind(Kind.INTERNAL)
```
Comment (trask) [inline instrumentation/servlet/src/main/java/io/opentelemetry/auto/instrumentation/servlet/http/HttpServletInstrumentation.java:101]: this is the default
```suggestion
```
